### ISSUE TITLE
Add a release , plz

### ISSUE THREAD

**Issue by kmahyyg** [CzBiX/peanut-link#1]
In the convenience of non-Android Developer,Please add a pre-compile version(apk package) in release,thx.

**Comment by CzBiX** [comment]
官方已经可以免客户端登陆了，此项目没有意义了，已放弃。

**Comment by kmahyyg** [comment]
Thx a lot.In Kunming,it must login in the client.Cannot use web login.

2016年11月15日 21:24，"CzBiX" notifications@github.com写道：

**Comment by CzBiX** [comment]
已上传 [release](https://github.com/CzBiX/peanut-link/releases/tag/release)。
不过版本有点老了，不知道还能正常使用不。

**Comment by kmahyyg** [comment]
非常感谢。Closed #1.

2016年11月23日 16:16，"CzBiX" notifications@github.com写道：
